config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'quests#index'

  # More specific routes
  get '/users/requests', to: 'users#requests', as: 'user_requests'
  get '/users/my_bookings', to: 'users#my_bookings', as: 'my_bookings'
  get 'profile', to: 'pages#profile', as: 'profile'

  # Quests routes
  get 'quests/new', to: 'quests#new', as: 'new_quest'
  post '/quests', to: 'quests#create', as: 'quests'
  get '/quests', to: "quests#index"
  get '/quests/:id', to: 'quests#show', as: 'quest'
  
  # Booking routes
  get '/quests/:id/bookings/new', to: 'bookings#new', as: 'new_booking'
  post '/quests/:id/bookings', to: 'bookings#create', as: 'bookings'
  get '/bookings', to: 'bookings#index'
  get '/bookings/:id', to: 'bookings#show', as: 'booking'
  post '/bookings/:id/accept', to:'bookings#accept', as: 'accept_booking'
  post '/bookings/:id/decline', to: 'bookings#decline', as: 'decline_booking'
  post '/bookings/:id/complete', to: 'bookings#complete', as: 'complete_booking'
  post '/bookings/:id/cancel', to:'bookings#cancel', as: 'cancel_booking'
  delete '/bookings/:id', to: 'bookings#destroy', as: 'delete_booking'

  # User routes
  get '/users/:id', to: 'users#show', as: 'user'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :quest
  belongs_to :user
end

app/models/quest.rb
class Quest < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  include PgSearch::Model
  pg_search_scope :search,
    against: [ :name, :description, :requirement ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :quests, foreign_key: :user_id, dependent: :destroy
  has_many :bookings, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :accept, :decline]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @quest = Quest.find(params[:quest_id])
  end


  def create
    @booking = Booking.new(booking_params)
    @booking.quest = Quest.find(params[:booking][:quest_id])
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking), notice: 'Enlistment was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: 'accepted')
    redirect_back(fallback_location: root_path, notice: 'Enlistment accepted')
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update(status: 'declined')
    redirect_back(fallback_location: root_path, notice: 'Enlistment declined')
  end

  def complete
  @booking = Booking.find(params[:id])
  if @booking.status == 'accepted'
    current_user_purse = current_user.purse || 0
    if current_user_purse >= @booking.quest.reward
      @booking.update(status: 'completed')
      current_user.purse -= @booking.quest.reward
      @booking.user.purse += @booking.quest.reward
      current_user.save
      @booking.user.save
      redirect_back(fallback_location: root_path, notice: 'Reward was sent successfully!')
    else
      redirect_back(fallback_location: root_path, notice: 'Insufficient coins in your purse.')
    end
  else
    redirect_to booking_path(@booking), notice: 'Reward was not sent. Enlistment not accepted yet.'
  end
end

  def cancel
    @booking = Booking.find(params[:id])
    if @booking.user == current_user
      @booking.update(status: 'cancelled')
      redirect_to my_bookings_path, notice: 'Enlistment was successfully withdrawn.'
    else
      redirect_to my_bookings_path, alert: 'You are not able to withdraw this enlistment.'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy
      redirect_to user_requests_path(current_user), notice: 'Enlistment was sent to the void.'
    else
      redirect_to user_requests_path(current_user), alert: 'Unable to remove the enlistment.'
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:message, :status, :quest_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def profile
    @user = current_user

    render 'profile'
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController

  def index
    @quests = Quest.all
    if params[:sort] == 'asc'
      @quests = Quest.order(reward: :asc)
    elsif params[:sort] == 'desc'
      @quests = Quest.order(reward: :desc)
    end
    if params[:query].present?
      @quests = Quest.search(params[:query])
    end
  end

  def new
    @quest = Quest.new
  end

  def create
    @quest = Quest.new(quest_params)
    @quest.user = current_user

    if @quest.save
      flash[:notice] = "Quest was successfully created!"
      redirect_to quest_path(@quest[:id])
    else
      render :new
    end
  end

  def show
    @quest = Quest.find(params[:id])
  end

  private

  def quest_params
    params.require(:quest).permit(:user_id, :name, :description, :requirement, :location, :reward)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy

  end

  def requests
    @user = current_user
    @bookings = Booking.where(quest: @user.quests)
  end

  def my_bookings
    @bookings = current_user.bookings
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_color_class(status)
    case status
    when 'accepted'
      'text-success'
    when 'declined'
      'text-danger'
    when 'pending'
      'text-primary'
    else
      ''
    end
  end
end

app/helpers/quests_helper.rb
module QuestsHelper
  def display_coins(reward)
    if reward < 500
      image_tag('coin.png', alt: '1x coin', width: '20px', height: '20px')
    elsif reward >= 500 && reward < 1000
      image_tag('coin.png', alt: '2x coin', width: '20px', height: '20px') * 2
    elsif reward >= 1000 && reward < 1500
      image_tag('coin.png', alt: '3x coin', width: '20px', height: '20px') * 3
    else
      image_tag('coin.png', alt: '4x coin', width: '20px', height: '20px') * 4
    end
  end
end

app/views/bookings/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card p-4">
        <h1 class="mb-4">Enlist for the Quest: <%= @quest.name %></h1>

        <%= form_for @booking, url: bookings_path do |f| %>
          <div class="form-group">
            <p class="form-control-static"><%= current_user.username.capitalize %>, are you prepared to enlist on the quest of the <%= @quest.name %>, for a reward of <%= @quest.reward %> coins? <%= display_coins(@quest.reward) %></p>
            <p>This quest requires a <strong><%= @quest.requirement.split(',').map(&:strip).join(' or a ') %></strong>, and you are a <%= current_user.character_class %>.
              <% if @quest.requirement.split(',').map(&:strip).include?(current_user.character_class) %>
                You are prepared to enlist for this quest!
              <% else %>
                You are not prepared!
              <% end %>
              </p>
            <%= f.hidden_field :quest_id, value: @quest.id %>
            <%= f.hidden_field :status, value: "pending" %>
          </div>

          <div class="form-group">
            <%= f.label :message, "Tell the Quest Master why they should send you on this quest!" %>
            <%= f.text_area :message, class: "form-control" %>
          </div>

          <%= f.submit 'Enlist', class: 'btn-purple btn-block' %>
        <% end %>

        <%= link_to "Back to Quest Board", quests_path, class: "btn-purple mt-3", style: "width: 200px;" %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card p-4">
        <p><strong><%= @booking.user.username.capitalize %></strong> the <%= @booking.user.character_class %>, you have enlisted for the quest <%= link_to @booking.quest.name, quest_path(@booking.quest) %>!</p>
        
        <p>Quest Master <strong><%= @booking.quest.user.username.capitalize %></strong> will review your enlistment.</p>

        <%= link_to 'Go to Quest Log', my_bookings_path, class: 'btn-purple' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hire a Hero</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag 'quests', media: 'all' %>
</head>

<body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
  <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Hire A Hero</h1>

app/views/pages/profile.html.erb
<div class="profile-container">
    <div class="profile-card">
        <h1 class="username">
            <%= @user.username.capitalize %>'s Profile
        </h1>

        <div class="profile">
            <p><%= @user.profile %></p>
        </div>

        <div class="level">
            <p><strong>Level:</strong> <%= @user.level %></p>
        </div>

        <div class="character_class">
            <p><strong>Class:</strong> <%= @user.character_class %></p>
        </div>

        <div class="abilities">
            <ul>
                <div><strong>Abilities:</strong></div>
                <% @user.abilities.split(',').map(&:strip).each do |ability| %>
                    <div><%= ability %></div>
                <% end %>
            </ul>
        </div>

        <div class="stats">
            <p><strong>Stats:</strong></p>
                <% @user.stats.each do |attribute, value| %>
                    <div><strong><%= attribute.capitalize%>:</strong> <%= value %></div>
                <% end %>
        </div>
    </div>
</div>

app/views/quests/index.html.erb
<div class="banner-area">
  <h1>Quest Board</h1>
  <p class='banner-text'>Heroes brave, the call has come, golden coins for deeds well done!</p>
  <div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: quests_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search-bar",
        placeholder: "Search for a quest..."
      %>
      <% if user_signed_in? && current_user.role == "dm" %>
        <%= link_to "Post a quest!", new_quest_path, class: "btn-purple-search" %>
      <% end %>
    <% end %>
    </div>
  </div>
  </div>
</div>

<div class="sort">
    <%= image_tag 'coin.png', alt: 'Coin', cwidth: '30px', height: '30px' %> Show me rewards:
    <%= select_tag :sort, options_for_select([
        ['Modest to Magnificent', 'asc'],
        ['Magnificent to Modest', 'desc'],
        ['Unsorted', '']
      ], selected: params[:sort]), onchange: 'window.location.href = "?sort=" + this.value;' %>
  </div>

<div class="index-container">
  <div class="card-row">
    <% @quests.each do |quest| %>
      <div class="card-container">
        <div class="card colour-card">
          <% if quest.photo.key %>
            <%= cl_image_tag quest.photo.key, class:"card-img-top", height: 400, width: 300 %>
          <% else %>
            <%= image_tag 'card-placeholder.png', class:"card-img-top", height: 400, width: 300  %>
          <% end %>
          <div class="card-body">
            <p class="card-title"><%= quest.name %></p>
            <p class="card-text"><%= truncate(quest.description, length: 120) %></p>
            <p class="card-text"><strong>Class requirement:</strong> <%= quest.requirement %></p>
            <p class="card-text"><strong>Reward:</strong> <%= quest.reward %> coins <%= display_coins(quest.reward) %></p>
            <%= link_to 'View Quest', quest_path(quest), class: "btn-purple btn-bottom-right" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/quests/new.html.erb
<div class="bookings-banner">
  <h1>Post a Quest</h1>
  <p class='banner-text'>Seeking heroes for a noble quest, come forth and put your skills to the test..</p>
  <div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    </div>
  </div>
  </div>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card p-4 colour-card">
      <%= image_tag 'new-quest.png', alt: 'Quest Scroll', class: 'new-quest', style: 'width: 100px; height: 100px;' %>
        <p>Quest Master <strong><%= current_user.username.capitalize%></strong>, please enter the details of your quest!</p>

        <%= form_for @quest do |f| %>

          <div class="form-group">
            <%= f.label :name, "Quest Name" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :description, "Quest Description" %>
            <%= f.text_area :description, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :requirement, "Class Requirement" %>
            <%= f.text_area :requirement, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :location, "Quest Location" %>
            <%= f.text_field :location, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :reward %>
            <%= f.number_field :reward, class: "form-control" %>
          </div>

          <div class="form-group">
          <%= f.file_field :photo%>

          <%= f.submit "Create Quest", class: "btn purple" %>

        <% end %>
      </div>
    </div>
  </div>
</div>
<br>

app/views/quests/show.html.erb
<div class="top-container">
  <div class="container-md">
    <div class="quest-card">
      <div class="left-side">
      <h1><%= @quest.name %></h1><br>
        <% if @quest.photo.key %>
          <%= cl_image_tag @quest.photo.key, class:"show-card-img-top", height: 400, width: 300 %>
        <% else %>
          <%= image_tag 'card-placeholder.png', class:"show-card-img-top", height: 400, width: 300 %>
        <% end %>
      </div>
      <div class="right-side">
        <div class="description">
          <p><%= @quest.description %></p>
          <div class="details">
            <div>
              <strong>Class Requirement</strong>
              <p><%= @quest.requirement %></p>
            </div>
            <div>
              <strong>Location</strong>
              <p><%= @quest.location %></p>
            </div>
            <div>
              <strong>Reward</strong>
              <p><%= @quest.reward %> coins <%= display_coins(@quest.reward) %></p>
            </div>
            <div>
              <strong>Quest Master</strong>
              <p><%= @quest.user.username.capitalize %></p>
            </div>
          </div>
          <%= link_to 'Enlist on this Quest', new_booking_path(quest_id: @quest.id), class: 'btn-purple' %>
          <%= link_to "Return to Quest Board", quests_path, class: "btn-purple" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent", style="">
    <ul class="navbar-nav">
      <li class="nav-item">
          <%= link_to image_tag('logo.png', alt: 'Logo', class: 'navbar-logo'), root_path, class: 'nav-link' %>
        </li>
      <% if user_signed_in? %>
          <%= link_to 'Quest Board', quests_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if current_user.role == 'dm' %>
            <%= link_to 'Enlistments', user_requests_path, class: "nav-link" %>
          <% else %>
            <%= link_to 'Quest Log', my_bookings_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to 'Profile', profile_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
        </li>    
      <% end %>
    </ul>
    <ul class="navbar-nav ms-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <span class="welcome-text">Welcome, <%= current_user.username.capitalize %>!</span>
        </li>
        <li class="nav-item">
          &nbsp;
        </li>
        <li class="nav-item">
          <span class="welcome-text">You have <%= current_user.purse %>&nbsp;<%= image_tag 'coin.png', alt: 'Coin', cwidth: '25px', height: '25px' %>&nbsp;</span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/my_bookings.html.erb
<div class="bookings-banner">
  <h1>Quest Log</h1>
  <p class='banner-text'>From quests begun to triumphs won..</p>
  <div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    </div>
  </div>
  </div>

<div class="index-container">
  <div class="card-row">
    <% @bookings.each do |booking| %>
      <div class="card-container">
        <div class="card colour-card ">
          <%= cl_image_tag booking.quest.photo.key, height: 300 %>
          <div class="card-body">
            <h2 class="card-title">Quest: <%= booking.quest.name %></h2>
            <p class="card-text"><%= truncate(booking.quest.description, length: 200) %></p>
            <p class="card-text"><strong>Quest Master:</strong> <%= booking.quest.user.username.capitalize %></p>
            <p class="card-text"><strong>Requirement:</strong> <%= booking.quest.requirement %></p>
            <p class="card-text"><strong>Reward:</strong> <%= booking.quest.reward %> coins <%= display_coins(booking.quest.reward) %></p>
            <strong>Enlistment Status:<p class="card-text <%= status_color_class(booking.status) %>"><%= booking.status.capitalize %></strong></p>
            
            <% if booking.status == 'pending' || booking.status == 'accepted' %>
              <%= button_to 'Withdraw from Quest', cancel_booking_path(booking), method: :post, class: 'btn-purple btn-bottom-right' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/requests.html.erb
<div class="enlistments-banner">
  <h1>Enlistments</h1>
  <p class='banner-text'>Here, adventurers enlisted stand, ready for the quest at hand...</p>
  <div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    </div>
  </div>
  </div>

<div class="index-container">
  <div class="card-row">
    <% @bookings.each do |booking| %>
      <div class="card-container">
        <div class="card colour-card">
          <%= cl_image_tag booking.quest.photo.key, height: 300 %>
          <div class="card-body">
            <h5 class="card-title">Quest: <%= link_to booking.quest.name, quest_path(booking.quest) %></h5>
            <p class="card-text"><strong>Enlisting Hero:</strong> <%= booking.user.username.capitalize %>, the level <%= booking.user.level %> <%= booking.user.character_class.capitalize %>.</p>
            <p class="card-text"><strong>Class Requirement:</strong> <%= booking.quest.requirement %></p>
            <p class="card-text"><strong>Message:</strong> <%= booking.message %></p>
            <strong>Enlistment Status:<p class="card-text <%= status_color_class(booking.status) %>"><%= booking.status.capitalize %></strong></p>
  
            <% if booking.status == 'pending' %>
              <%= button_to 'Accept', accept_booking_path(booking), method: :post, class: 'btn-purple' %>
              <%= button_to 'Decline', decline_booking_path(booking), method: :post, class: 'btn-purple' %>
            <% elsif booking.status == 'accepted' %>
              <%= button_to 'Send the hero their reward!', complete_booking_path(booking), method: :post, class: 'btn-purple' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/view_profile.html.erb
<!-- app/views/users/view_profile.html.erb -->
<h1>User Profile</h1>

<% if @current_action == "view_purse" %>
  <h2>:: Purse ::</h2>
  <p>Coins: <%= @coins %></p>
<% end %>

<% if @current_action == "view_stats" %>
  <h2>:: Stats ::</h2>
  <p>Power: <% @user.power %></p>
  <p>Agility: <% @user.agility %></p>
  <p>Haste: <% @user.haste %></p>
<% end %>

<% if @current_action == "view_abilities" %>
  <h2>:: Abilities ::</h2>
  <ul>
    <li>Fire Blast</li>
    <li>Fire Hurricane</li>
    <li>Fire Bolt</li>
  </ul>
<% end %>